### ISSUE TITLE
Cannot install cfg2html 2.99 on CentOS7 or RedHat 7

### ISSUE THREAD

**Issue by jadupl2** [cfg2html/cfg2html#110]
Hi,
Great Product but only version 1.79 OLD version work on RHEL 7 or CentOS7.
Can you Help me ?

root@centos7/sadmin/pkg/cfg2html# rpm -ivh cfg2html-linux-2.94-2.noarch.rpm
Preparing...                          ################################# [100%]
    file / from install of cfg2html-linux-2.94-2.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64
    file /usr/bin from install of cfg2html-linux-2.94-2.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64
root@centos7/sadmin/pkg/cfg2html# rpm -ivh cfg2html-linux-2.54-1.noarch.rpm
Preparing...                          ################################# [100%]
    file / from install of cfg2html-linux-2.54-1.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64
    file /usr/bin from install of cfg2html-linux-2.54-1.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64
root@centos7/sadmin/pkg/cfg2html#

**Comment by roseswe** [comment]
Is this fixed with 2.9x or 6.2x??  Will investigate that issue on CentOS 7

**Comment by zchef2k** [comment]
In the meantime, obtain 'rpmrebuild' and edit the specfile of the original rpm on the fly. Delete the lines in the specfile that install /, /etc, and /usr/bin. The packages should no longer trigger conflicts with 'filesystem'.

**Comment by jadupl2** [comment]
Thank You Very Much, it is appreciated

**Comment by gdha** [comment]
@jadupl2 why don't you switch to **6.*** release of _cfg2html_ available at http://download.opensuse.org/repositories/home:/gdha/CentOS_7/noarch/

**Comment by roseswe** [comment]
Closing, unrelated to cfg2html 6.xx stream
