### ISSUE TITLE
collect info around Veritas cluster

### ISSUE THREAD

**Issue by gdha** [cfg2html/cfg2html#111]
VCS server info collections like `/etc/llthosts` , `/etc/llttab`, `hastatus`, `haclus -display` and other stuff I am not (yet) aware of?

**Comment by azmim** [comment]
It would be great if able to capture several syntax from engine_A logs.

**Comment by roseswe** [comment]
~/cfg2html/cfg2html > grep -r hastatus *
sunos/plugins/VCS_plugin.sh:	hastatus -sum

**Comment by azmim** [comment]
cool, but its under sunos.. does it only for sun server?

**Comment by roseswe** [comment]
I assume it will work out of the box.  For Linux this must be tested by someone that has a Veritas Cluster.  The script must be enhanced (case statements).

**Comment by roseswe** [comment]
As nobody contributes, I close this one!
