### ISSUE TITLE
systemd services restart

### ISSUE THREAD

**Issue by zchef2k** [cfg2html/cfg2html#112]
On systems with systemd, running cfg2html causes services to appearently re-init. Why is this and what portion of the script is responsible for it?

**Comment by gdha** [comment]
@zchef2k are you able to proof this via some logs (journalctl)? Interesting to have a better view of your problem...

**Comment by zchef2k** [comment]
This run id from 6.27-git201601061610 but have also observed it in the 2.99 version. And perhaps I misspoke. It's not all services restarting, but some being spawned and through dbus:

See the time I ran the script:

[root@<redacted> 09:21:32 ~]
# /usr/sbin/cfg2html

See journalctl output almost immediately afterwards: 

Apr 06 09:21:40 hostname.is.redacted myusername[32612]: Start of 6.27-git201601061610
Apr 06 09:21:40 hostname.is.redacted myusername[32627]: Start of 6.27-git201601061610
Apr 06 09:21:40 hostname.is.redacted dbus[1102]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedeskt
Apr 06 09:21:40 hostname.is.redacted dbus-daemon[1102]: dbus[1102]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit=
Apr 06 09:21:40 hostname.is.redacted systemd[1]: Starting Hostname Service...
Apr 06 09:21:40 hostname.is.redacted dbus[1102]: [system] Successfully activated service 'org.freedesktop.hostname1'
Apr 06 09:21:40 hostname.is.redacted dbus-daemon[1102]: dbus[1102]: [system] Successfully activated service 'org.freedesktop.hostname1'
Apr 06 09:21:40 hostname.is.redacted systemd[1]: Started Hostname Service.
Apr 06 09:21:40 hostname.is.redacted dbus[1102]: [system] Activating via systemd: service name='org.freedesktop.machine1' unit='dbus-org.freedeskto
Apr 06 09:21:40 hostname.is.redacted dbus-daemon[1102]: dbus[1102]: [system] Activating via systemd: service name='org.freedesktop.machine1' unit='
Apr 06 09:21:41 hostname.is.redacted systemd[1]: Starting Virtual Machine and Container Registration Service...
Apr 06 09:21:41 hostname.is.redacted dbus[1102]: [system] Successfully activated service 'org.freedesktop.machine1'
Apr 06 09:21:41 hostname.is.redacted dbus-daemon[1102]: dbus[1102]: [system] Successfully activated service 'org.freedesktop.machine1'
Apr 06 09:21:41 hostname.is.redacted systemd[1]: Started Virtual Machine and Container Registration Service.
Apr 06 09:21:59 hostname.is.redacted systemd[1]: Configuration file /usr/lib/systemd/system/wpa_supplicant.service is marked executable. Please rem
Apr 06 09:21:59 hostname.is.redacted systemd[1]: Configuration file /usr/lib/systemd/system/ebtables.service is marked executable. Please remove ex
Apr 06 09:22:09 hostname.is.redacted dbus[1102]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedeskt
Apr 06 09:22:09 hostname.is.redacted dbus-daemon[1102]: dbus[1102]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit=
Apr 06 09:22:09 hostname.is.redacted systemd[1]: Starting Time & Date Service...
Apr 06 09:22:09 hostname.is.redacted dbus[1102]: [system] Successfully activated service 'org.freedesktop.timedate1'
Apr 06 09:22:09 hostname.is.redacted dbus-daemon[1102]: dbus[1102]: [system] Successfully activated service 'org.freedesktop.timedate1'
Apr 06 09:22:09 hostname.is.redacted systemd[1]: Started Time & Date Service.

**Comment by gdha** [comment]
@zchef2k you could use the `-T` to trace timings in the output. That way you can drill down what sub-commands triggers this side effect.

**Comment by gdha** [comment]
No feedback since long time - let us close it - it can be re-opnened if required
