### ISSUE TITLE
add /etc/netgroup to the collection

### ISSUE THREAD

**Issue by gdha** [cfg2html/cfg2html#118]
We miss the content of the file `/etc/netgroup`

**Comment by gdha** [comment]
Perhaps we could add this one to `$CONFIG_DIR/files` file?

**Comment by roseswe** [comment]
According to the tags this affects only HP-UX?
As HP-UX is "dead" is it OK to close this issue?

**Comment by gdha** [comment]
@roseswe HP-UX is not complete dead yet, but I agree it is not important anymore so we can close this issue.
