### ISSUE TITLE
Add support for VIOS data collection

### ISSUE THREAD

**Issue by pkx616** [cfg2html/cfg2html#119]
cfg2html should be able to collect VIOS data.
I know VIOS is an AIX with additional software, and cfg2html is able to collect AIX-related information.
But it doesn't collect any VIOS specific data (IOS software level, virtual devices configuration, etc).

**Comment by gdha** [comment]
@pkx616 Are you able to prepare a pull request with the things you have in mind?

**Comment by roseswe** [comment]
No user feedback, closed
