### ISSUE TITLE
$CONFIG_DIR/files missing in package

### ISSUE THREAD

**Issue by roseswe** [cfg2html/cfg2html#122]
When playing around with the fix for /etc/cfg2html/files I realised that the dummy file for "files" is missing and also not included into the make/build process.

Reference: 40efa356816fe48064887b4d7e10c283049f1017

**Comment by gdha** [comment]
@roseswe is it OK now?

**Comment by roseswe** [comment]
We have now two "files". Closing this issue. We can open an new one regarding the two files if needed.

/cfg2html/cfg2html > find . -name files
./linux/etc/files
./linux/files
