### ISSUE TITLE
Two debian package directories exists, also related to issue #35

### ISSUE THREAD

**Issue by roseswe** [cfg2html/cfg2html#128]
I assume one tree is obsolete and can removed from git?

/cfg2html/cfg2html/linux > find .| grep -i debian
./debian
./debian/README.Debian
./debian/changelog
./debian/copyright
./debian/compat
./debian/control
./debian/cfg2html.dsc
./debian/dirs
./debian/conffiles
./debian/docs
./debian/rules
./packaging/debian
./packaging/debian/README.Debian
./packaging/debian/changelog
./packaging/debian/copyright
./packaging/debian/compat
./packaging/debian/control
./packaging/debian/cfg2html.dsc
./packaging/debian/dirs
./packaging/debian/conffiles
./packaging/debian/docs
./packaging/debian/rules

**Comment by gdha** [comment]
@roseswe The `./debian/` is obsolete as we use the `packaging/debian' directory to build

**Comment by roseswe** [comment]
Thanks for clarifying. Removed from by Dev tree. Didn't see it any longer in Git, so closing #128
