### ISSUE TITLE
suggestion : for AIX systems use "who -b" to track last reboot date and time

### ISSUE THREAD

**Issue by JediNite** [cfg2html/cfg2html#133]
Currently on AIX the following is run when reporting reboots:

```
$ last | grep boot
reboot    ~                                   Aug 18 21:13
reboot    ~                                   Jul 31 19:38
reboot    ~                                   Apr 10 15:26
reboot    ~                                   Dec 14 16:50
```

If the wtmp file is cleared or cycled due to an execessive amount of logins, this command can sometimes return back empty.

The "who -b" command may be a better command to run:

```
$ who -b
   .        system boot Aug 18 21:13
```

**Comment by roseswe** [comment]
Should be closed with
commit 8cbfd97dd86ab16aa4aedca332ed44e47dc132d4
Author: roseswe <3810660+roseswe@users.noreply.github.com>
Date:   Tue Mar 12 18:49:47 2019 +0100

    new: added who -b, suggested by JetiNite

**Comment by JediNite** [comment]
Ralph,

The change looks good to me.  If I get a chance I'll download it and run it on a server we have access to.

Cheers,

JediNite

**Comment by JediNite** [comment]
Just tested it and the output looks fine.  Closing the issue!
