### ISSUE TITLE
Phyical Hosts reported as Virtual

### ISSUE THREAD

**Issue by frankcrawford** [cfg2html/cfg2html#142]
During the testing for Physical vs Virtual machine, there is a specific test for the message "Booting paravirtualized kernel on bare hardware", which sets certain virtualization settings, and ultimately lead to the host being listed as Virtual, however, is this correct?

It the test really for a virtualized kernel or a physical host?  At a minimum the output should included details that it is bare hardware.

**Comment by edrulrd** [comment]
Try this now.  It works on my CentoOS 7 and 8 physical and virtual systems after my recent updates.  Thanks. Ed

**Comment by frankcrawford** [comment]
> Try this now. It works on my CentoOS 7 and 8 physical and virtual systems after my recent updates. Thanks. Ed

Sorry, it took a while to get back to this, and yes the version in git seems to fix the issue for me.

Thanks.

**Comment by roseswe** [comment]
Thanks for the feedback, thus closing.
