### ISSUE TITLE
suggestion: add different outputs?

### ISSUE THREAD

**Issue by DigBaddy72** [cfg2html/cfg2html#151]
Was wondering if it would be possible to allow different outputs besides html?  Like json or xml ?  I know that goes beyond the name of the tool, but it would be AWESOME to be able to then use the output in a db query.

**Comment by roseswe** [comment]
All output is done via the function _exec_command()_
So if you want JSON/XML whatever, you "simply" have to extend the exec_command function to do that. An example is the creation of "TXT" output of this function.

**Comment by roseswe** [comment]
long runner, closed
