### ISSUE TITLE
The link to the CFG2HTML issues page is broken in the text of the welcome page. It includes a trailing dot.

### ISSUE THREAD

**Issue by glennhuxtable** [cfg2html/cfg2html#152]
The github welcome page (whatever) has a paragraph:

_**Issue Tracker**
If you find a problem or bug, want to discuss feature requests, or have some bright new ideas, please create a new issue on our GitHub project page **https://github.com/cfg2html/cfg2html/issues.** When using it, please ensure that any criticism you provide is constructive. Please do not use the issue tracker for general help and assistance with using cfg2html.

Feel free to open a pull request to fix a problem yourself or to contribute a new feature.__

The link to the issue page has a trailing "." which breaks the link.

**Comment by roseswe** [comment]
Thanks for reporting this. Should be fixed now. OK2Close?
