### ISSUE TITLE
minor bug in cfg2html-linux.sh guessing virtualisation type from /var/log/dmesg

### ISSUE THREAD

**Issue by glennhuxtable** [cfg2html/cfg2html#153]
Sorry, don't have GIT set up in my current environment, so I will have to do this the hard way ...

Lines 298 to 315 of cfg2html-linux.sh say:

      # These are only indented this way so as to visually distinguish them; there is no desire/need to if-then-else them!
      if [ -n "${DMESG}" -a "$(${DMESG} | grep -i ${VIRTs})" ]; then # typo fixed on 20201004 by edrulrd
           # Using the 'dmesg' command is useful for some number of days after the system was last booted; # typo fixed on 20201004 by edrulrd
           # beyond that, the /var/log/dmesg file is a good alternate datapoint.
           if [ ! "$(${DMESG} | grep 'Booting paravirtualized kernel on bare hardware')" ]; then # typo fixed on 20201004 by edrulrd
                # This exception catches the one case of installing RHEL/CentOS on a real physical machine.  This IS properly/necessarily nested!
                VIRTterm='TRUE'
                VIRTdc='TRUE'
           fi
      fi

      if [ "$(grep -i ${VIRTs} /var/log/dmesg 2>/dev/null)" ]; then
           **if [ ! "$(${DMESG} | grep 'Booting paravirtualized kernel on bare hardware')" ]; then**
                  # This exception catches the one case of installing RHEL/CentOS on a real physical machine.  This IS properly/necessarily nested!
                  VIRTterm='TRUE'
                  VIRTdf='TRUE'
           fi
      fi

I believe the highligted line (line 310 in the file) should read:
        if [ ! "$(grep 'Booting paravirtualized kernel on bare hardware' /var/log/dmesg )" ]; then

It appears the first "if" is searching the output of running "dmsg", and the second if is testing pretty much the same stuff but  searching the contents of var/log/dmesg file itself.

The he line in question appears to have been copy/pasted without adjusting for searching /var/log/dmesg.

The original incorrectly classifies a REHL physical server as a virtual server, however with this correction it correctly identifies the server as physical.

**Comment by edrulrd** [comment]
issue confirmed.  After clearing kernel ring buffer with "dmesg -C", same result occurs on CentOS 7 on real hardware - reports as being virtual.  Will plan to submit a fix.

**Comment by gdha** [comment]
@glennhuxtable  `/var/log/dmesg` is not always available on all distro's, therefore using the `dmesg` command is much safer.

**Comment by gdha** [comment]
A possible solution could be using the same trick as done in https://github.com/gdha/upgrade-ux/issues/135

**Comment by roseswe** [comment]
Should be fixed with the edrulrd commits around 20201004
