### ISSUE TITLE
Running on RHEL 8 hangs

### ISSUE THREAD

**Issue by johnknall** [cfg2html/cfg2html#154]
I've installed version 6.41.1.21.ga7a6c5f-1 via rpm from cfg2html.com.  When I run it the output directory and files are created but then it just hangs.  When I look at running processes more and more cfg2html process are spawned.  Collection never finishes and nothing except the system name is in the files.

![cfg2html_rhel8](https://user-images.githubusercontent.com/10185877/112325515-2475af80-8c8a-11eb-8ae2-3bdfa930f0f9.png)

**Comment by gdha** [comment]
@roseswe it works for me on many RHEL 8 systems. Must have been HW related thing - next time ask for the error file which is most likely showing where it gets stuck.

**Comment by roseswe** [comment]
Please reopen if problem exits with full logs provided
