### ISSUE TITLE
added option of "?" broke options below

### ISSUE THREAD

**Issue by edrulrd** [cfg2html/cfg2html#165]
Hi Ralph,

unfortunately, changing the help option a couple weeks ago in cfg2html-linux.sh ( that is, adding "|?" to  the h option), so that it is now "h|?" is being taken as a wildcard and no options below the help option h are now available for use!

Appreciate you removing these 2 extra characters to the command options.  [ They aren't really needed, since if an option is  improper, it provides help anyway, so adding the "?" really doesn't add much.

Here's the diff showing the issue after I changed it on my system:

# diff cfg2html-linux.sh.org cfg2html-linux.sh
98c98
<     h|?   ) echo ${_VERSION}; usage; exit 0;;
---
>     h     ) echo ${_VERSION}; usage; exit 0;;

Thanks,
Ed

**Comment by roseswe** [comment]
Thanks Ed for opening this issue. Can you confirm it is fixed with commit [acd47f2](https://github.com/cfg2html/cfg2html/commit/acd47f2aa2b64cabb2af72ad6ef043a9df4f4c8b)
