### ISSUE TITLE
Queries using virsh may hang forever

### ISSUE THREAD

**Issue by frankcrawford** [cfg2html/cfg2html#168]
There is a known issue that if `libvirtd` is not running and `virsh` is run it may hang forever, which will hang `cfg2html`.

This may be cause by `libvirtd` crashing, or just having virtualisation installed but not running.

Simplest fix may be to setup some sort of time out for it.

**Comment by frankcrawford** [comment]
I've done PR #169 which should fix it.

**Comment by frankcrawford** [comment]
P.S. I've picked a timeout of 20sec at random.  If you can suggest a better time, feel free.

**Comment by roseswe** [comment]
Thanks, I will close this issue, should be fixed with the MR
