### ISSUE TITLE
System Info

### ISSUE THREAD

**Issue by jim347lps** [cfg2html/cfg2html#171]
In the Red Hat rpm there is a "/etc/cfg2html/systeminfo" file for edit, why this does not exist in the Ubuntu Debian flavor of the cfg2html ??

**Comment by roseswe** [comment]
According to cfg2html/linux/packaging/debian/conffiles there should be /etc/cfg2html/systeminfo

**Comment by jim347lps** [comment]
I just installed it on a new Debian Ubuntu ver 20.04.5 LTS system with "apt install" and the install package does not create a file in "/etc/cfg2html/" with name systeminfo.

**Comment by roseswe** [comment]
Is /etc/cfg2html created at all?

**Comment by jim347lps** [comment]
Yes that directory is created ok.  The "systeminfo" template file is not there.

**Comment by roseswe** [comment]
OK to close?

**Comment by jim347lps** [comment]
I hope it gets fixed on the next release,  Yes OK, and thanks for your reply.

**Comment by roseswe** [comment]
See https://www.cfg2html.com/  -> [cfg2html_7.0.2_all.deb](https://www.cfg2html.com/cfg2html_7.0.2_all.deb)

cfg2html for Linux - Debian package format (Ubuntu, Debian, Mint etc.)  (BETA. May fix issue #171)
