### ISSUE TITLE
linux contrib

### ISSUE THREAD

**Issue by tyl0re** [cfg2html/cfg2html#174]
Question: on linux there are many script in 
/cfg2html/linux/contrib
Like for example
Linux-audit-account-password-hashing.pl

On Hp i find somthing like
```
if [ -x /usr/contrib/bin/show_patches ]
    then
        show_patches -a
        echo " "
        show_patches -s
        echo "\n"

    fi
```
On Linux i don't find any code loading the contrib. How can they be loaded?

**Comment by roseswe** [comment]
Contrib script are bonus programs and NOT used directly by cfg2html itself.
Need to update the documentation
