### ISSUE TITLE
linux/doc/cfg2html.txt missing

### ISSUE THREAD

**Issue by gdha** [cfg2html/cfg2html#19]
In the linux/doc tree there is now a file called `cfg2html-Linux_deutsch.txt` which is partially in German language and is quite outdated. We should write a new `cfg2html.txt` file (in ASCIIDOC) to explain the basics of cfg2html. The txt file will be automatically translated into a HTML file (by the make process).
I (gdha) will write the initial headers, but hoping that Ralph can add some useful info to it.

**Comment by roseswe** [comment]
File is there. Needs rework. But lets close this old issue.
