### ISSUE TITLE
# zcat /boot/initrd | cpio -t | grep \.ko$

### ISSUE THREAD

**Issue by roseswe** [cfg2html/cfg2html#26]
Could this be an usefull addition?

```
# zcat /boot/initrd | cpio -t | grep \.ko$
lib/modules/3.0.74-0.6.10-default/kernel/lib/crc-t10dif.ko
lib/modules/3.0.74-0.6.10-default/kernel/fs/ext3/ext3.ko
lib/modules/3.0.74-0.6.10-default/kernel/fs/mbcache.ko
lib/modules/3.0.74-0.6.10-default/kernel/fs/jbd/jbd.ko
```

**Comment by gdha** [comment]
@roseswe `lsinitrd -l /boot/initrd` shows also the same output as with `/bin/zcat /boot/initrd | cpio -itv 2>/dev/null`
However, I'm not yet convinced of the added value (I needed to rebuild the initrd [with the help of rear] on SLES 11 for SAP after some failed updates - boot disk was not recognized anymore).
Could you explain which added value we may expect?
