### ISSUE TITLE
Collect ProLiant RBSU (BIOS) configuration if CONREP utility is available

### ISSUE THREAD

**Issue by tzong** [cfg2html/cfg2html#34]
On a ProLiant with HP Scripting Toolkit (former SSSTK) installed CONREP utility could save RBSU (BIOS) configuration to archive. Code should look something like:

```
    HPCONREP=$(which hp-conrep 2>/dev/null )
    if [ -x "$HPCONREP" ] ; then
            $HPCONREP -s -f $temphp/conrep.dat
    fi
```

hp-conrep is only available when STK is installed from rpm (see SDR for downloads). If installed from tar.gz, more sophisticated code is needed.

**Comment by roseswe** [comment]
Anybody able to test this with a ProLiant?

**Comment by tzong** [comment]
I confirm that correct conrep.dat is added to the archive. Checked on ProLiant ML350 G6.
