### ISSUE TITLE
openSUSE Build System (OBS): Debian build fails

### ISSUE THREAD

**Issue by gdha** [cfg2html/cfg2html#35]
Debian build fails on OpenSuSe Build System, but it works fine via `make deb` command. We get the following error:

```
[   32s] # copy cfg2html components into directories
[   32s] cp -av etc/default.conf debian/cfg2html/etc/cfg2html/
[   32s] cp: cannot stat `etc/default.conf': No such file or directory
[   32s] make: *** [binary-indep] Error 1
[   32s] dpkg-buildpackage: error: fakeroot-tcp debian/rules binary gave error exit status 2
```

See also: https://build.opensuse.org/package/show/home:gdha/cfg2html

Any hints are more then welcome!

**Comment by gdha** [comment]
````
[  171s] if [ $(basename $(pwd)) = "BUILD" ]; then \
[  171s] 		cd linux ; \
[  171s] 		ls -l ; \
[  171s] 	fi
[  171s] total 200
[  171s] -rw-r--r-- 1 root root   1941 May 15  2014 AUTHORS
[  171s] -rw-r--r-- 1 root root  35147 Jul  1  2007 COPYING
[  171s] -rw-r--r-- 1 root root  10261 Aug 14  2014 Makefile
[  171s] -rw-r--r-- 1 root root  12448 Oct  8  2013 README
[  171s] -rwxr-xr-x 1 root root 101465 Mar  5 04:05 cfg2html-linux.sh
[  171s] drwxr-xr-x 2 root root   4096 Mar 27 13:24 collect
[  171s] drwxr-xr-x 4 root root   4096 Mar 27 13:24 contrib
[  171s] drwxr-xr-x 2 root root   4096 Mar 27 13:24 doc
[  171s] drwxr-xr-x 2 root root   4096 Mar 27 13:24 etc
[  171s] drwxr-xr-x 2 root root   4096 Mar 27 13:24 lib
[  171s] drwxr-xr-x 4 root root   4096 Mar 27 13:24 packaging
[  171s] -rw-r--r-- 1 root root    534 May 15  2014 plugins
[  171s] -rw-r--r-- 1 root root    242 Feb 22  2014 systeminfo
[  171s] # copy cfg2html components into directories
[  171s] cp -av etc/default.conf debian/cfg2html/usr/share/cfg2html/etc/cfg2html/
[  171s] cp: cannot stat `etc/default.conf': No such file or directory
[  171s] make: *** [binary-indep] Error 1
````
unfortunately, not the golden bullet

**Comment by gdha** [comment]
````
[  104s] debian/cfg2html/var/log/cfg2html:
[  104s] total 0
[  104s] # copy cfg2html components into directories
[  104s] pwd
[  104s] /usr/src/packages/BUILD
[  104s] cp -av etc/default.conf debian/cfg2html/usr/share/cfg2html/etc/cfg2html/
[  104s] cp: cannot stat `etc/default.conf': No such file or directory
````
we should go 1 directory higher (`cd linux`)

**Comment by roseswe** [comment]
Still open/an issue? OK to close?

**Comment by gdha** [comment]
It still fails:
````
   64s] dh_clean
[   64s] 	rm -f debian/debhelper-build-stamp
[   64s] 	rm -f debian/cfg2html.substvars
[   64s] 	rm -f debian/cfg2html.*.debhelper
[   64s] 	rm -rf debian/cfg2html/
[   64s] 	rm -rf debian/.debhelper/
[   64s] 	rm -f debian/*.debhelper.log
[   64s] dh_clean: Please specify the compatibility level in debian/compat
[   64s] debian/rules:46: recipe for target 'clean' failed
````

**Comment by roseswe** [comment]
Should be fixed now. Please try!
 174062 Jan 15 11:45 cfg2html_6.33-1_all.deb
 191419 Jan 15 11:44 cfg2html-6.33-git201801151142.tar.gz

**Comment by gdha** [comment]
@roseswe not really at OBS - see
https://build.opensuse.org/package/live_build_log/home:gdha/cfg2html/Debian_7.0/x86_64
Can you see the content?

**Comment by roseswe** [comment]
Yes, this is strange. It build on my "normal" Debian 8 system. This is the part causing the error:

[   77s] /usr/src/packages/BUILD
[   77s] cp -av etc/default.conf debian/cfg2html/usr/share/cfg2html/etc/cfg2html/
[   77s] cp: cannot stat `etc/default.conf': No such file or directory
[   77s] make: *** [binary-indep] Error 1

See also commit:
  [master 802e83c] Hopefully a bug fix for issue #35
  and issue #128

**Comment by gdha** [comment]
@roseswe I see that the debian/ubuntu builds are failing on OBS with an error:
````
[   78s] files 329448263a3fef4b2f9825e92da31110 195883 cfg2html_6.33_8_gfed2d16.orig.tar.gz
[   78s] Scanning //usr/src/packages/SOURCES.DEB/cfg2html_6.33_8_gfed2d16.orig.tar.gz...
[   78s] Generating //usr/src/packages/SOURCES.DEB/cfg2html_6.33_8_gfed2d16-0git201802082250.diff
[   78s] Processing file "//usr/src/packages/SOURCES/debian.rules"...
[   78s] Processing file "//usr/src/packages/SOURCES/debian.control"...
[   78s] Processing file "//usr/src/packages/SOURCES/debian.changelog"...
[   78s] Writing //usr/src/packages/SOURCES.DEB/cfg2html_6.33_8_gfed2d16-0git201802082250.dsc
[   79s] dpkg-source: warning: extracting unsigned source package (/usr/src/packages/SOURCES.DEB/cfg2html_6.33_8_gfed2d16-0git201802082250.dsc)
[   79s] dpkg-source: error: version number contains illegal character `_'
[   79s] dpkg-source: info: extracting cfg2html in /usr/src/packages/BUILD
[   79s] -----------------------------------------------------------------
[   79s] ----- building cfg2html.dsc (user abuild)
[   79s] -----------------------------------------------------------------
[   79s] -----------------------------------------------------------------
[   79s] -su: line 0: cd: /usr/src/packages/BUILD: No such file or directory
````

**Comment by roseswe** [comment]
Found this line in the OBS log:  dpkg-source: warning: BUILD/debian/changelog(l5): badly formatted trailer line

**Comment by roseswe** [comment]
With osc build Debian_9.0 I got this hint:

[    2s] dh_clean
[    2s] 	rm -f debian/debhelper-build-stamp
[    2s] 	rm -f debian/cfg2html.substvars
[    2s] 	rm -f debian/cfg2html.*.debhelper
[    2s] 	rm -rf debian/cfg2html/
[    2s] 	rm -rf debian/.debhelper/
[    2s] 	rm -f debian/*.debhelper.log
[    2s] dh_clean: Please specify the compatibility level in debian/compat
[    2s] debian/rules:47: recipe for target 'clean' failed
[    2s] make: *** [clean] Error 2
[    2s] dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
[    2s] 
[    2s] dell failed "build cfg2html.dsc" at Tue Jun 12 12:59:51 UTC 2018.

**Comment by roseswe** [comment]
Closing. If it problem still exists please open an new issue

**Comment by gdha** [comment]
See http://download.opensuse.org/repositories/home:/gdha/ for the packages build for the different OSes.

**Comment by roseswe** [comment]
Linux Mint Debian Edition 5 (elsie -> bullseye)

- dh_installdirs: warning: Compatibility levels before 10 are deprecated (level 9 in use)
- cp: cannot stat 'linux/etc/default.conf': No such file or directory
- make: *** [Makefile:34: deb] Error 2

**Comment by gdha** [comment]
@roseswe is now working on command line `make deb` and also via OBS.
