### ISSUE TITLE
Add SAP collection stuff

### ISSUE THREAD

**Issue by roseswe** [cfg2html/cfg2html#38]
/usr/sap/hostctrl/exe/saphostexec  -version
/usr/sap/hostctrl/exe/saphostexec  -status

ps fax | grep <SID>
etc.

**Comment by gdha** [comment]
For HP-UX it is done - removed the label. Linux is not done yet.

**Comment by roseswe** [comment]
Gratien to which one did you refer?  get_sap.sh or get_sap_info.sh?
Maybe we should consolidate both to one plug-in. and also add it to all streams.

Also we can add new stuff like 
sapcontrol -nr <nr> -function HAGetFailoverConfig

**Comment by roseswe** [comment]
Another approach is to use the "Supportconfig Plugin for SUSE SAP (HANA)" as a template

**Comment by roseswe** [comment]
Closing, if this is still an open issue we must re-open a new one.
