### ISSUE TITLE
ll /etc/alternatives/

### ISSUE THREAD

**Issue by roseswe** [cfg2html/cfg2html#45]
add a 
~> ll /etc/alternatives/|grep -v .gz$
insgesamt 4
lrwxrwxrwx 1 root root  9  6. Mär 2013  awk -> /bin/gawk
lrwxrwxrwx 1 root root 13  6. Mär 2013  ftp -> /usr/bin/pftp
lrwxrwxrwx 1 root root 29  6. Mär 2013  gst-install-plugins-helper -> /usr/lib/pk-gstreamer-install
lrwxrwxrwx 1 root root 34  6. Mär 2013  gtk-update-icon-cache -> /usr/bin/gtk-update-icon-cache-3.0
lrwxrwxrwx 1 root root 41 29. Mär 2013  java -> /usr/lib64/jvm/jre-1.7.0-openjdk/bin/java

**Comment by frankcrawford** [comment]
@roseswe what is the question here?  I think we do need to add some reference to alternatives some where in the output.

**Comment by roseswe** [comment]
So let's add this to the Linux collector :-)

**Comment by roseswe** [comment]
long runner, closed
