### ISSUE TITLE
stale NFS causes cfg2html to hang

### ISSUE THREAD

**Issue by gdha** [cfg2html/cfg2html#51]
in the error file we see:
````
2014-03-05 12:41:27   0 secs: cat /var/adm/sw/needs_config
2014-03-05 12:41:34   7 secs: patch_stat
````
on the screen we see:
````
Collecting:  Filesystems, Dump and Swap Configuration
NFS server bl870ci2 not responding still trying
````
This has probably to do with several `df` or `bdf` commands, or we need to replace these with `mount` or introduce a kind of `timeout` function or executable

**Comment by roseswe** [comment]
ok2close?
