### ISSUE TITLE
cfg2html hangs on SUSE distros with zypper/package kit, you must manual press enter

### ISSUE THREAD

**Issue by roseswe** [cfg2html/cfg2html#6]
Applies for the 5.x and 6.x stream.

maybe: ps -ef| grep .... ?

PackageKit is blocking zypper. This happens if you have an updater applet or other software management application using PackageKit running.
Tell PackageKit to quit? [yes/no](no):

**Comment by gdha** [comment]
@roseswe Any update?

**Comment by roseswe** [comment]
We have added "timeout(1)" around zypper. No feedback (negative) since years, so closing this issue!
