### ISSUE TITLE
Test of sendmail Version Generates Empty Emails

### ISSUE THREAD

**Issue by frankcrawford** [cfg2html/cfg2html#80]
The test of the sendmail version in the Linux version causes an empty email to be sent to root.

Almost exactly the same result could be obtained with the command "sendmail -bs < /dev/null".

**Comment by roseswe** [comment]
Can you please confirm if commit b2f7560 fixes this issue? Thanks!

**Comment by frankcrawford** [comment]
No unfortunately it doesn't.

The basic problem is that currently to test what version of sendmail is
running you invoke it in send mode, which will always send an empty
message.  My suggestion is to run it in SMTP mode which it starts by
printing out the version information and then waiting.

Regards
Frank

**Comment by daVikes** [comment]
I am seeing something similar with 2.94-2.     It says: "Mail Delivery Status Report"  in the email which is going to the root mailbox.  Looking at the subject it says "probe"  

Is there a way to disable it temp. on the 2.94-2 version?

Thanks!

**Comment by frankcrawford** [comment]
The fix I suggested was to run sendmail in "stand-alone SMTP server"
mode (i.e. add "-bs" option), but this seems to have been ignored.

Frank

**Comment by daVikes** [comment]
I temporary went back to the old line in the script which redirected it to dev/null.  Not a long term fix as each time its upgraded or new version it would have to be changed again.  However, I'm not sure what the intention was though?  If it was to just get the version info? Or if it was to actually do send a test email ?   It would be nice to select which you would like to do in a config file perhaps.

Thanks!

**Comment by roseswe** [comment]
regarding the old cfg2html version - we are currently at 2.99 which isn't released yet and this also contains the sendmail bug.

regarding the 6.xx - Frank maybe you can fix it and provide a merge pull request for all?

**Comment by frankcrawford** [comment]
Okay, I'll see what I can do in the near future, although I will note
that from what I see, the aim is to just find the sendmail version.

Regards
Frank

**Comment by daVikes** [comment]
Thanks for the update Frank.  That helps.   

To get the sendmail version maybe:
sendmail -d0.1 -bt < /dev/null

could also grep that so
sendmail -d0.1 -bt < /dev/null | grep Version


Postfix maybe:

postver=`postconf -d | grep -v "milter_macro_v" | grep -i "mail_version" | awk '{print $3}'`

or there is always:


rpm -qa | grep -i postfix
rpm -qa | grep -i sendmail

**Comment by gdha** [comment]
On HP-UX this works what @daVikes suggusted:
````
$ /usr/lib/sendmail -d0.1 -bt < /dev/null | grep Version
Version @(#)Sendmail version 8.13.3 - Revision 1.004:: HP-UX11.31 - 03rd February,2010
````

**Comment by frankcrawford** [comment]
Interestingly on Linux it only gives:
Version 8.15.2
It doesn't include the sendmail.cf version, but saying that, it is far
better than the current method, and good enough for general use.
Regards
Frank

**Comment by gdha** [comment]
Will not modify the current code on HP-UX as it works fine - no need to break something that works.
I have no Linux systems using the old sendmail - only postfix...

**Comment by frankcrawford** [comment]
I was just looking at what is in the HP-UX version, and combined with @daVikes and @gdha comment above it would give a good listing for Linux of the version without my original issue of emailing random messages.  It would pick up the sendmail build version and then grep the config file version (c.f. grep ^DZ /etc/mail/sendmail.cf).

**Comment by frankcrawford** [comment]
Okay, after a bit of a break here, I'd propose the following patch for managing the MTA section, making use of some of the code from the HP-UX version.

What do you think of this patch based on the latest RPM?

[cfg2html-linux-mta.diff.txt](https://github.com/cfg2html/cfg2html/files/222600/cfg2html-linux-mta.diff.txt)

**Comment by gdha** [comment]
@frankcrawford Sounds good - why don't you prepare a pull request? Makes life so much easier for us!

**Comment by frankcrawford** [comment]
@gdha yep will do.  I put up the patch mainly to see if anyone had any comments on it before actually doing a pull request.

**Comment by roseswe** [comment]
Please provide a pull request. The diff and the current version are IMHO out of sync.

**Comment by frankcrawford** [comment]
Okay, PR created.

**Comment by daVikes** [comment]
Was looking at #115 and this part didn't seem to work on RH6.6

if [ -d /etc/alternatives ]; then
  MTA=$(alternatives --list | grep mta | cut -d'        ' -f3)
fi

was getting:
cut: the delimiter must be a single character
Try `cut --help' for more information.


Looking at options I don't have a list, although I do see display

usage: alternatives --install <link> <name> <path> <priority>
                    [--initscript <service>]
                    [--slave <link> <name> <path>]*
       alternatives --remove <name> <path>
       alternatives --auto <name>
       alternatives --config <name>
       alternatives --display <name>
       alternatives --set <name> <path>

common options: --verbose --test --help --usage --version
                --altdir <directory> --admindir <directory>


It seems like the next section covered it though.  

if  [ -z "$MTA" ]; then
  if [ -x /usr/sbin/postconf ]; then
       MTA='sendmail.postfix'
  elif [ -f /usr/sbin/sendmail.sendmail ]; then
       MTA='/usr/sbin/sendmail/sendmail.sendmail'
  elif [ -x /usr/sbin/sendmail ]; then
       MTA='/usr/sbin/sendmail'
  fi
fi

as I get : 

MTA:  sendmail.postfix

then:

2.6.6

For the output.

So not sure if that can be simplified ?

Then the other case statement had 3 different exec_commands in it ?  So it would try each one ? Is that right?   Also, what if both are "installed"  ?

Thanks!

**Comment by daVikes** [comment]
came up with a script if this is somewhat helpful.   I see there is some additional syntax for cfg2html for exec_command but that could be added back into this.  



#!/bin/sh

postfixInstalled=`rpm -qa | grep postfix | wc -l`
sendmailInstalled=`rpm -qa | grep sendmail | wc -l`

if [ $postfixInstalled -eq 1 ]; then
 if [ -x /usr/sbin/postconf ]; then
   postVer=`/usr/sbin/postconf -h mail_version`
   echo "Postfix Version: $postVer"
 fi
else
 echo "Postfix Not Installed"
fi

if [ $sendmailInstalled -eq 1 ]; then

 if [ -f /usr/sbin/sendmail.sendmail ]; then
     MTA='/usr/sbin/sendmail.sendmail'
   elif [ -x /usr/sbin/sendmail ]; then
     MTA='/usr/sbin/sendmail'
 fi

 if [ ! -z $MTA ]; then
    echo "MTA: " $MTA
    sendmailVer=`$MTA -d0.1 -bv root | head -1`
    echo "Sendmail Verison: $sendmailVer"
 else
   echo "Sendmail Not Found"
 fi

else
 echo "Sendmail Not Installed"
fi

**Comment by daVikes** [comment]
Added the exec_command.    Sorry, not a dev, just a admin that would like this to work =)

I did try this, and seemed to work for me.


 postfixInstalled=`rpm -qa | grep postfix | wc -l`
 sendmailInstalled=`rpm -qa | grep sendmail | wc -l`
 if [ $postfixInstalled -eq 1 ]; then
  if [ -x /usr/sbin/postconf ]; then
    exec_command "/usr/sbin/postconf -h mail_version" "Postfix version"
  fi
 fi

 if [ $sendmailInstalled -eq 1 ]; then
  if [ -f /usr/sbin/sendmail.sendmail ]; then
     MTA='/usr/sbin/sendmail.sendmail'
   elif [ -x /usr/sbin/sendmail ]; then
     MTA='/usr/sbin/sendmail'
  fi
  if [ ! -z $MTA ]; then
    exec_command "$MTA -d0.1 -bv root | head -1" "Sendmail Version"
  fi
 fi

**Comment by frankcrawford** [comment]
@daVikes unfortunately if both are installed, your last version gives no idea of which is the correct MTA.  As well, not all systems support rpm, so again there is a problem with generalities.

I'll look at the alternatives options again, I wasn't aware of how they changed over time.

**Comment by frankcrawford** [comment]
Looking at it, I should be able to completely do away with the alternatives call, as it just prints out details on the symlink.  I'll just update the script to deal directly with the symlink.

So, wait for a new version, in a day or so.

**Comment by frankcrawford** [comment]
@daVikes I've created a new PR that should fix the issue.  Does this work better?

I guess the issue is still outstanding about what to report if both sendmail and postfix are installed.

**Comment by roseswe** [comment]
Frank thanks! Can anybod confirm that the bug is gone/still there?

**Comment by roseswe** [comment]
Fixed? OK to close?

**Comment by frankcrawford** [comment]
As far as I'm concerned, yes.
