### ISSUE TITLE
Feedback/Question on security command line switch

### ISSUE THREAD

**Issue by roseswe** [cfg2html/cfg2html#83]
From Frank (April 2015):
I notice that recent versions of cfg2html-linux (and probably others) it
includes /etc/shadow and similar files in the clear in the output and
the only way to suppress it is to suppress all system information, which
loses a lot of the usefulness of cfg2html.

There are two possibilities, which aren't exclusive, either to add an
option to not include such security files, and/or add something to
obscure the actual encrypted passwords, e.g. by replacing them with the
string "suppressed".

So, what do others feel and what other items should be covered by similar protection?

**Comment by roseswe** [comment]
For a security audit I need to see which hash algo. the customer uses. Normally cfg2html is run by root and the files are stored by root, so no additional security issue..... :-)

**Comment by frankcrawford** [comment]
It isn't an issue about who it is stored by, but who can read the files.  The default for the RPM certainly are accessible by all.

However, from you comment are you mainly interested in the algorithm?  In which case the "suppression" I mentioned could be a bit more complicated and leave the header information, but suppress the actual encryption part.

**Comment by gdha** [comment]
@frankcrawford could you show an example - it is probably me, but I'm not following what you request?

**Comment by frankcrawford** [comment]
It is a bit hard but the issue I'm trying to address is that in recent
versions in include the contents of /etc/shadow, with no way to easily
stop it.  I'm suggesting an option specifically not include
/etc/shadow, although also was thinking of an option to obfuscate the
hash in /etc/shadow rather than not print the entire file.
Unfortunately, I haven't had any time so far to try and code up for it
yet.
Regards
Frank

**Comment by tbrix32** [comment]
Frank>… was thinking of an option to obfuscate the hash in /etc/shadow

one could let awk print all fields except $2, like
kong:~ # awk -F":" '{print $1 FS FS $3 FS $4 FS $5 FS $6 FS $7 FS $8 }' /etc/shadow | head
at::15869:0:99999:7::
bin::15385:::::
daemon::15385:::::
ftp::15385:::::
games::15385:::::
gdm::15869:0:99999:7::
haldaemon::15385:0::7::
lp::15385:::::
mail::15385:::::
man::15385:::::
kong:~ #

compared to

kong:~ # head /etc/shadow
at:*:15869:0:99999:7:::
bin:*:15385::::::
daemon:*:15385::::::
ftp:*:15385::::::
games:*:15385::::::
gdm:*:15869:0:99999:7:::
haldaemon:*:15385:0::7:::
lp:*:15385::::::
mail:*:15385::::::
man:*:15385::::::
kong:~ #

Would that come close to what you need?
Kind regards
Thomas

**Comment by frankcrawford** [comment]
Thomas,
Yep, pretty much.  I was thinking it may be worth only doing it if
there was a "valid password" in the password field, that way you could
at least tell if the blank, locked, etc.  However, that is a nice to
have, what you have done is the basics of what I think is needed.
Regards
Frank

**Comment by tbrix32** [comment]
that one simply replaces field two with “x”.
We set the output field separator OFS to equal FS “:” to preserve the line format

awk -F":" 'BEGIN{OFS=FS}{$2="x"; print $0}' /etc/shadow

one could add a bit of logic there:
  awk -F":" 'BEGIN{OFS=FS}{if ( $2 != "*" ) $2="x"; print $0}' /etc/shadow

guess I’d favor the latter.

**Comment by frankcrawford** [comment]
Yep, the second one is a little better, but either would do.
Regards
Frank

**Comment by gdha** [comment]
`awk -F":" 'BEGIN{OFS=FS}{if ( $2 != "*" ) $2="x"; print $0}' /etc/shadow` is my favorite too.
