### ISSUE TITLE
aix - forgotten escapes?

### ISSUE THREAD

**Issue by jose1711** [cfg2html/cfg2html#86]
i discovered i had to escape awk's positional arguments in both:
exec_command "who -r | awk '{print $2,$3}" "Current runlevel"
and
exec_command "ps -e -o ruser,pid,args | awk ' (($1+1) > 1) {print \$0;} '" "P...

to get output on aix 7.1 system. lines after modification:
exec_command "who -r | awk '{print \$2,\$3}" "Current runlevel"
exec_command "ps -e -o ruser,pid,args | awk ' ((\$1+1) > 1) {print \$0;} '" "P...

**Comment by roseswe** [comment]
I am not sure if this is the root cause, but I changed this in the c0e5d8befe commit
Could you please test, as I am not able to access an AIX system for testing.

**Comment by jose1711** [comment]
well... i tested before reporting. with unescaped arguments i was getting no output for runlevel and error in log, now it's fine
