### ISSUE TITLE
aix - top load processes parses ps output incorrectly

### ISSUE THREAD

**Issue by jose1711** [cfg2html/cfg2html#87]
in cfg2html-aix.sh does not really make much sense - at least not on our aix 7.1 and 5.3 installation. consider example output of ps -ef:
    root  2556092        1   0   Oct 30      -  0:00 /usr/lib/errdemon
    root  2621576        1   0   Oct 30      -  1:05 /usr/sbin/cron
    root  2687182        1   0   Oct 30      -  0:00 /usr/sbin/strerr

cut -c39- gives you:
0      -  0:00 /usr/lib/errdemon
0      -  1:05 /usr/sbin/cron
0      -  0:00 /usr/sbin/strerr

looking at linux script i think you want TIME column in aix as well, that is:
       time
            Indicates the cumulative CPU time since the process started. The time is displayed in the same format as in etime. The default header for this field is TIME.
then this could be changed to
ps -e -o time,comm | sort -nr | head -25

example output:
   01:24:55 syncd
   00:30:20 getty
   00:20:38 issDaemon
   00:14:06 rmcd

**Comment by roseswe** [comment]
It seems that the AIX version needs a lot of rework. As I have no AIX system to test: Could you be so kind and fetch the last version (git pull) and fix the AIX stuff and upload it via a pull request? Thanks a lot!
